name: Sample Python

on: [push]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
    - name: Test with pytest
      run: |
        python3 test_hello.py
